### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by mangusbrother** [teal77/trireme#10]
I have a raspberry pi set up with a deluge daemon.

If i connect from my desktop using the deluge app as a thin client it works fine. 

From trireme however i can add my server successfully to the server list, but when i go back to the home page (or restart app) it states :
SSL Handshake exception, certificate was changed  on the remote server.

and doesn't load anything.

**Comment by mangusbrother** [comment]
First time using the app

**Comment by teal77** [comment]
Thanks, I think the issue is in upstream.
https://github.com/dart-lang/sdk/issues/35462

For now, you'll have to use the app without pinning the certificate.
![screenshot_20190104-110143_deluge](https://user-images.githubusercontent.com/29652669/50675713-c5c6ab80-1015-11e9-9944-486310d5ddb9.png)

Uncheck the "Save certificate" toggle.
It was optional to begin with, I'll mention it clearly in the next version.

**Comment by dga4130-renato** [comment]
I have a similar problem. It's not connecting.
If I use another pc with deluge installed and I try to login rpc to my server it works . But using this app from my smartphone it timeouts with no connect.
I tested inside the net. So it's not a router configuration problem.

**Comment by teal77** [comment]
What's your deluge version?

**Comment by dga4130-renato** [comment]
2.0 dev

**Comment by dga4130-renato** [comment]
Running under Ubuntu 18.10

**Comment by teal77** [comment]
Thanks, looks deluge 2.0 connection is completely broken.

**Comment by dga4130-renato** [comment]
Strange because from another deluge installed in a different  pc works fine

**Comment by dga4130-renato** [comment]
Can you email cas about this ?

**Comment by teal77** [comment]
See #14 
The dart implementation of deluge client was broken because of changes made upstream. It's not a problem with your deluge installation, but instead a problem with this app.
